---
name: WebDAO
version: 1.01
author:
  - 'Zahatski Aliaksandr, E<lt>zag@cpan.orgE<gt>'
abstract: platform for easy creation of high-performance and scalable web applications
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0.37
  DateTime::Format::HTTP: 0.37
  Encode: 0
  FCGI: 0.67
  Getopt::Long: 2.35
  XML::LibXML: 0
provides:
  Apache::Directives2:
    file: lib/Apache/Directives2.pm
  Apache::WebDAO:
    file: lib/Apache/WebDAO.pm
  WebDAO:
    file: lib/WebDAO.pm
    version: 1.01
  WebDAO::Base:
    file: lib/WebDAO/Base.pm
  WebDAO::CVapache2:
    file: lib/WebDAO/CVapache2.pm
  WebDAO::CVcgi:
    file: lib/WebDAO/CVcgi.pm
  WebDAO::Comp::ListEnv:
    file: lib/WebDAO/Comp/ListEnv.pm
  WebDAO::Component:
    file: lib/WebDAO/Component.pm
  WebDAO::Container:
    file: lib/WebDAO/Container.pm
  WebDAO::Element:
    file: lib/WebDAO/Element.pm
  WebDAO::Engine:
    file: lib/WebDAO/Engine.pm
  WebDAO::FCGI::ProcManager:
    file: lib/WebDAO/FCGI/ProcManager.pm
    version: 0.17
  WebDAO::Lex:
    file: lib/WebDAO/Lex.pm
  WebDAO::Lexer::Lbase:
    file: lib/WebDAO/Lexer/Lbase.pm
  WebDAO::Lexer::Linclude:
    file: lib/WebDAO/Lexer/Linclude.pm
  WebDAO::Lexer::Lmethod:
    file: lib/WebDAO/Lexer/Lmethod.pm
  WebDAO::Lexer::Lobject:
    file: lib/WebDAO/Lexer/Lobject.pm
  WebDAO::Lexer::Lobjectref:
    file: lib/WebDAO/Lexer/Lobjectref.pm
  WebDAO::Lexer::Lregclass:
    file: lib/WebDAO/Lexer/Lregclass.pm
  WebDAO::Lexer::Ltext:
    file: lib/WebDAO/Lexer/Ltext.pm
  WebDAO::Lib::MethodByPath:
    file: lib/WebDAO/Lib/MethodByPath.pm
  WebDAO::Lib::RawHTML:
    file: lib/WebDAO/Lib/RawHTML.pm
  WebDAO::Response:
    file: lib/WebDAO/Response.pm
  WebDAO::Session:
    file: lib/WebDAO/Session.pm
  WebDAO::SessionID:
    file: lib/WebDAO/SessionID.pm
  WebDAO::SessionSH:
    file: lib/WebDAO/SessionSH.pm
  WebDAO::Sessionco:
    file: lib/WebDAO/Sessionco.pm
  WebDAO::Store::Abstract:
    file: lib/WebDAO/Store/Abstract.pm
  WebDAO::Store::Storable:
    file: lib/WebDAO/Store/Storable.pm
  WebDAO::Test:
    file: lib/WebDAO/Test.pm
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
